#ifndef __MY_MAIN_TASK_DATA_STRUCT_H_20200308_FHQ__
#define __MY_MAIN_TASK_DATA_STRUCT_H_20200308_FHQ__
#include "MyGlobalDefine.h"
#include "MyCompilerDefine.h"

#if defined(__cplusplus)
extern "C" {     
#endif
#define MAX_BT_NAME 31
#define TRACKIMO_GSENSOR_SILENT_TIME 60

typedef enum{
TIMER_SECOND_HR,
TIMER_SECOND_MAX,
}enumMainTaskSecondTimer;

typedef enum{
	CHARGE_ERROR_NOERROR,
	CHARGE_ERROR_LOW_VOLTAGE,
	CHARGE_ERROR_HIGH_VOLTAGE,
	CHARGE_ERROR_TEMPERATURE,
	CHARGE_ERROR_TIME,
}enumChargeError;


typedef enum{
POWERSTEP_WELCOM,
POWERSTEP_POWERON,
POWERSTEP_SHUTDOWNING,
POWERSTEP_SHUTDOWN,
}enumPowerStep;

typedef enum {
	SYSTEM_EVENT_REBOOT,
	SYSTEM_EVENT_SHUTDOWN,							//关机
	SYSTEM_EVENT_LOW_POWER,						//低电,跟电量
	SYSTEM_EVENT_CHARGE_CONNECTED,					//充电连接
	SYSTEM_EVENT_CHARGE_DISCONNECTED,				//充电断连
	SYSTEM_EVENT_CHARGE_FULL,						//充电完成
	SYSTEM_EVENT_CHARGE_ERROR,						//充电错误
	SYSTEM_EVENT_START_MOVING,
	SYSTEM_EVENT_STOP_MOVING,
	SYSTEM_EVENT_MAX,
} enumSystemEvent;

typedef enum {
	CLOCK_EVENT_SECOND_CHANGE,
	CLOCK_EVENT_MINUTE_CHANGE,
	CLOCK_EVENT_UTC_HOUR_CHANGE,
	CLOCK_EVENT_UTC_DAY_CHANGE,
	CLOCK_EVENT_UTC_MONTH_CHANGE,
	CLOCK_EVENT_UTC_YEAR_CHANGE,
	CLOCK_EVENT_LOCAL_HOUR_CHANGE,
	CLOCK_EVENT_LOCAL_DAY_CHANGE,
	CLOCK_EVENT_LOCAL_MONTH_CHANGE,
	CLOCK_EVENT_LOCAL_YEAR_CHANGE,	
	CLOCK_EVENT_TIMEZONE_CHANGE,
	CLOCK_EVENT_MAX,
} enumClockEvent;

typedef enum {
	TRACKIMO_EVENT_QUIRE_POS,
	TRACKIMO_EVENT_MAX,
} enumTrackimoEvent;
typedef enum {
#ifdef SUPPORT_TIMER_EXCUTE_IN_TASK
	MAIN_MSG_INTASK_TIMER_CB,
#endif	
	MAIN_MSG_SYSTEM_EVENT,
	MAIN_MSG_POWERSTEP_EVENT,
	MAIN_MSG_AT_EVENT,
	MAIN_MSG_CLOCK_EVENT,
	MAIN_MSG_KEY_EVENT,
	MAIN_MSG_GPS_EVENT,
	MAIN_MSG_BLE_EVENT,
	MAIN_MSG_GSENSOR_EVENT,
	MAIN_MSG_WIFI_EVENT,
	MAIN_MSG_NG_EVENT,
	MAIN_MSG_TRACKIMO_EVENT,
	MAIN_MSG_MAX
 } enumMainMsg;

#define MAX_TRACKIMO_COUNT 10

BOOL main_task_is_queue_full(void);
BOOL main_task_is_queue_busy(void);
BOOL main_task_post_message(int msg, int wPara, int lpPara);

#if defined(__cplusplus)
}
#endif 

#endif //__MY_MAIN_TASK_DATA_STRUCT_H_20200308_FHQ__



